# Generated by Django 5.2.1 on 2025-05-28 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='is_ai',
            field=models.BooleanField(default=False),
        ),
    ]
