# Generated by Django 5.2.1 on 2025-05-28 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0002_chat_is_ai'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='previous_output_id',
            field=models.CharField(default=None, max_length=200),
        ),
    ]
