# Generated by Django 5.2.1 on 2025-05-30 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0003_chat_previous_output_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='updated_at',
        ),
    ]
