# Generated by Django 5.2.1 on 2025-05-26 11:31

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Essay',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=2047)),
                ('essay', models.CharField()),
                ('authors', models.CharField(max_length=255)),
                ('source_url', models.URLField(max_length=511)),
                ('thumbnail_url', models.URLField(max_length=511)),
            ],
        ),
    ]
