# Generated by Django 5.2.1 on 2025-06-13 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='context_response_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
